services:
  db:
    image: postgres:16
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: warehouse_web
    command: sh -c "python manage.py migrate --settings=config.settings_docker && python manage.py runserver 0.0.0.0:8000 --settings=config.settings_docker"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  tests:
    build: .
    container_name: warehouse_tests
    command: pytest -c core/pytest.ini core
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings_docker
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - test

volumes:
  postgres_data: