# Generated by Django 5.2.12 on 2026-03-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movementitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
                verbose_name="Товар",
            ),
        ),
    ]
